### ISSUE TITLE
Marketing - Improved upsell on taxonomy admin pages

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2266] opened 2019-03-08 14:18 UTC
In https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/738 we made an admin notice for taxonomy admin pages. We should designing explore better and more attractive options.

**Comment by arnaudbroes** [comment] 2020-03-11 19:39
Duplicate of https://github.com/awesomemotive/aioseop-pro/issues/72

**Closed by arnaudbroes** 2020-03-11 19:39 UTC
Labels: Priority | Medium, UX
