### ISSUE TITLE
XML Sitemap - New post (update?) should ping google, bing, etc

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#359] opened 2016-06-23 22:35 UTC
Currently, this is do_notify() in the sitemap class, although we could move it from there elsewhere... maybe even use do_notify as a wrapper function for sitemap purposes.

Ping about just the post or the entire sitemap?

**Comment by wpsmort** [comment] 2016-06-23 22:47
@michaeltorbert:
There's a post here by Google on best practices - https://webmasters.googleblog.com/2014/10/best-practices-for-xml-sitemaps-rssatom.html

In this post they state that you should update the sitemap at least once a day and ping Google after you update it.  It was this post that was the reason why we added the Schedule Updates option (https://semperplugins.com/documentation/xml-sitemaps-module/#schedule-updates) and gave users the choice of daily, weekly or monthly.  Hopefully we're using the ping method they describe here - http://www.sitemaps.org/protocol.html#submit_ping

If we ping on publish post then we should ping the entire sitemap as per the method they describe.  Alternatively we use the RSS/Atom feed method they describe.

**Comment by michaeltorbert** [comment] 2016-06-24 00:01
I *think we're already pinging them once a day (when we do the sitemap rebuild) but I'm not 100% positive.

**Comment by wpsmort** [comment] 2016-08-10 22:11
We discussed this today and agreed to remove the Schedule Updates option and have it default to weekly with a filter to change this although setting this to daily without a filter would also work.  See issue #425.

**Comment by wpsmort** [comment] 2016-10-07 23:46
Duplicate of #550

**Comment by michaeltorbert** [comment] 2016-10-27 13:55
Currently, pinging is heavily integrated with the building of static sitemaps. We should probably take care of this once we remove static.

**Comment by michaeltorbert** [comment] 2019-02-23 17:19
Related to #2219

**Comment by michaeltorbert** [comment] 2019-02-23 17:19
@wpsmort Why did we agree to default to weekly instead of daily?

**Comment by michaeltorbert** [comment] 2019-02-23 17:23
One thought... wouldn't pinging on update potentially make the save action time out with an excessively large sitemap? Should we have this add a cron event on save to do it a few minutes later in the background?

**Comment by arnaudbroes** [comment] 2019-08-14 18:03
I'll review this first to see what we are doing and what we could be doing also.

**Comment by wpsmort** [comment] 2020-04-29 21:06
Issue moved to [awesomemotive/aioseop-pro #910](https://github.com/awesomemotive/aioseop-pro/issues/910) via [**ZenHub**](https://www.zenhub.com/)

**Closed by wpsmort** 2020-04-29 21:06 UTC
Labels: Optimization
