### ISSUE TITLE
Conflict with Wholesale For WooCommerce

### ISSUE THREAD

**Issue by Garconis** [awesomemotive/all-in-one-seo-pack#3155] opened 2020-03-13 17:35 UTC
We are reaching out due to a bug we've noticed, that only occurs when All in One SEO Pack is installed.

When _Wholesale for WooCommerce_ and _All in One SEO Pack_ are installed, it causes the _Wholesale for WooCommerce_ to have a false error when registering a new user.

- https://woocommerce.com/products/wholesale-for-woocommerce/

With AIOSEO **activated**, the registration form (created by the wholesale plugin) throws an error when it shouldn't. It says the user already exists, when it doesn't. 

- Screenshot: https://gyazo.com/d9e0c47a99a09f19715a008f5d87647c

When AIOSEO is **deactivated** it works fine.
- Screenshot: https://gyazo.com/cb46ab15c68c64f3f4081964651713d5

If desired, you can test it out using a fake email.

- https://daythreebotanicals.com/wholesale-registration/

We've tested this on an install with:
- PHP 7.4
- Twenty Nineteen theme
- WooCommerce plugin
- Wholesale for WooCommerce plugin
- All in One SEO Pack plugin

**Comment by arnaudbroes** [comment] 2020-03-14 10:13
@Garconis could you check if the "Run Shortcodes in Autogenerated Descriptions" setting is enabled in the General Settings menu? I'm quite sure that could be the cause of this. If so, please let us know what shortcodes are used by that plugin and we'll add them to our list of shortcodes to ignore.

**Comment by Garconis** [comment] 2020-03-16 12:25
It was on, and we've since disabled it as you requested. 

But it's still not fixed completely:
https://gyazo.com/fd42765ea7cfb63b7eeee93ac1e38837

It deleted the error message above the header, but not above the form.

This is the only shortcode used:
`[wwp_registration_form]`

**Comment by wpsmort** [comment] 2020-03-20 18:18
@Garconis I tested this on a clone of your site on our test server and could not reproduce the problem.  I was able to register a user with no problem.  I then tested on your live site and it worked there too - https://a.supportally.com/7W7SsS

I'm closing this as it's not a problem with our plugin.

**Comment by Garconis** [comment] 2020-03-20 18:38
It's because we disabled the shortcode feature, as was previously requested. We are also hiding the false error that still shows, via CSS. So the issue still exists.

**Comment by wpsmort** [comment] 2020-03-20 18:42
I cannot reproduce the stated issue shown here - https://gyazo.com/fd42765ea7cfb63b7eeee93ac1e38837

Please provide the exact steps to reproduce this on your site.

**Comment by freshykarina** [comment] 2020-03-20 19:06
Hello!

**The original issue:**
[![Screenshot from Gyazo](https://gyazo.com/d9e0c47a99a09f19715a008f5d87647c/raw)](https://gyazo.com/d9e0c47a99a09f19715a008f5d87647c)
If the form submitted successfully, it still showed an error message. In two places. At the very top of the page and on top of the form.

**Right now if you complete the form it should look like this:**
[![Screenshot from Gyazo](https://gyazo.com/a80dedca00c046eb7397757939e68f9d/raw)](https://gyazo.com/a80dedca00c046eb7397757939e68f9d)

**If there was an error it looks like this:**
[![Screenshot from Gyazo](https://gyazo.com/d263c4a2f0019ca460c80a6eb1ac34ec/raw)](https://gyazo.com/d263c4a2f0019ca460c80a6eb1ac34ec)

**Steps I took:**
1. I checked on "Run Shortcodes in Autogenerated Descriptions".= with AISEO.
2. Did a new test, and got this result: [![Screenshot from Gyazo](https://gyazo.com/fd42765ea7cfb63b7eeee93ac1e38837/raw)](https://gyazo.com/fd42765ea7cfb63b7eeee93ac1e38837)
Note, that doing step 1 removed the error message at the top of the page but not the top of the form.
3. I hid the error message that appears at the top of the form with CSS.

The problem is the error message above the form still appearing even if the form is submitted successfully.

In your testing have you made the error message above the form visible again and tested?
If so, you should have seen the screenshot from step 2. 
If you DID make it visible again and can't replicate then I guess the problem is solved!

**Comment by wpsmort** [comment] 2020-03-20 19:22
I am now able to reproduce this.  

You can fix this on your site bu going to /wp-content/plugins/all-in-one-seo-pack/inc/ and editing the file called aioseop_functions.php

Scroll to line 1276 where you should see a line that says $conflicting_shortcodes.

Edit the code to look like this:

```
	$conflicting_shortcodes = array(
		'WooCommerce Login'          => '[woocommerce_my_account]',
		'WooCommerce Checkout'       => '[woocommerce_checkout]',
		'WooCommerce Order Tracking' => '[woocommerce_order_tracking]',
		'WooCommerce Cart'           => '[woocommerce_cart]',
		'WooCommerce Registration'   => '[wwp_registration_form]',
	);
``` 

Notice that we've added a new line called WooCommerce Registration.

We'll git a bug fix out for this soon.

**Comment by wpsmort** [comment] 2020-03-20 19:23
@arnaudbroes Do you want to quickly make this change so it gets into 3.4.

**Comment by freshykarina** [comment] 2020-03-20 19:49
Thanks all!!

**Closed** 2020-03-23 13:46 UTC
