### ISSUE TITLE
Bug - Redirect to about page is breaking following updates

### ISSUE THREAD

**Issue by Zodiac1978** [awesomemotive/all-in-one-seo-pack#2576] opened 2019-06-05 15:20 UTC
/wp-admin/index.php?page=aioseop-about

**Describe the bug**
In a bulk update from AIOSEOP and other plugins, the updates following after AIOSEOP are failing because of the redirect to the About page.

Related #2255

**To Reproduce**
1. Go to Plugins
2. Mark the plugins to update or click update link from AIOSEOP and at least one more plugin
3. See the second one failing - error message is showing the about page

**Expected behavior**
Updates shouldn't fail.

**Screenshots**
<img width="1223" alt="aioseop" src="https://user-images.githubusercontent.com/870475/58968323-2705cd00-87b6-11e9-91e3-76f02d95cda6.png">

**Comment by Zodiac1978** [comment] 2019-06-05 15:21
![aioseop](https://user-images.githubusercontent.com/870475/58968479-66ccb480-87b6-11e9-8ab3-abc8bc8432ae.gif)

**Comment by michaeltorbert** [comment] 2019-06-05 16:39
@Zodiac1978 Thanks for reporting this, and THANKS for the great steps to reproduce + animation. 
We're looking into it now.

**Comment by arnaudbroes** [comment] 2019-06-05 20:49
I'm not able to reproduce this issue. Here's what I did:

1. Install AIOSEOP, Classic Editor, Contact Form (same plugins as user);
2. Change version number of each plugin so they can be updated.
3. Go to the database and change the value of 'aioseop_seen_about_page' in the user meta table to an earlier version.

![image](https://user-images.githubusercontent.com/18156697/58989231-cbeacf00-87e3-11e9-90b3-9e8ea1a6380a.png)

**Comment by michaeltorbert** [comment] 2019-06-05 21:46
Hi @Zodiac1978 

So far we've been unable to reproduce this. You can submit your login info to our secure form here and we'll be happy to investigate further so we can get out a fix as quickly as possible: https://semperplugins.com/contact/support-login-information/

**Comment by wpsmort** [comment] 2019-06-05 22:09
I have been able to reproduce this on a local test site.  Here are the steps to reproduce this:

1. Install old versions of multiple plugins (NOTE: the plugins should have names that place them after All in One SEO Pack in the alphabetical list on the Plugins screen)
2. Install v2.12.1 of AIOSEOP
3. Go to the Plugins screen an verify that all plugins require updates
4. Select all of the plugins and then select Update in the Bulk Actions drop down and click Apply. See screenshot below.

<img width="1072" alt="Screen Shot 2019-06-05 at 6 08 07 PM" src="https://user-images.githubusercontent.com/17548525/58993933-f6756180-87bc-11e9-91a1-63273e0819fc.png">

5. Once AIO is updated, there's a pause before the redirect to the Welcome Screen happens, as that redirect happens during the update of one of the plugins, an Update Failed message is displayed.  See screenshot below.

<img width="1436" alt="Screen Shot 2019-06-05 at 6 08 32 PM" src="https://user-images.githubusercontent.com/17548525/58993948-03925080-87bd-11e9-8fbb-01be5133980b.png">

**Comment by Zodiac1978** [comment] 2019-06-06 08:00
> Select all of the plugins and then select Update in the Bulk Actions drop down and click Apply. See screenshot below.

The problem is showing too if you click the "update now" links manually to start the updates. You just have to start AIOSEOP first and then the other plugins to see the issue.

**Comment by michaeltorbert** [comment] 2019-06-06 12:30
@EkoJR When you tried and couldn't reproduce this, did you have AIOSEOP activated first?

**Comment by wpsmort** [comment] 2019-06-06 19:01
@EkoJR As discussed, I've given you access to a site where this can be reproduced.

**Comment by EkoJR** [comment] 2019-06-07 09:25
This is due to file permissions/owner, and does not appear to be related to AIOSEOP.

> Update Failed: The update cannot be installed because we will be unable to copy some files. This is usually due to inconsistent file permissions.

Plugin page with plugin updates
![i-2576-plugins-page](https://user-images.githubusercontent.com/2794445/59094596-53f7d400-88cb-11e9-9758-b2756922efd1.png)

File Right/Owner in FTP
![i-2576-ftp-perms](https://user-images.githubusercontent.com/2794445/59094625-64a84a00-88cb-11e9-9d11-8fc444b0d2fa.png)

**Comment by michaeltorbert** [comment] 2019-06-07 12:18
@EkoJR I think that's specific to your installation. I'm not getting that error message at all. I'm getting the one reported by @Zodiac1978

**Comment by EkoJR** [comment] 2019-06-07 20:08
@michaeltorbert I was able to get both errors on the remote test site. First one was for all plugin, which had the long error message, and the second was for the remaining plugin that didn't update (classic editor), which gave me that WP error.

**Comment by michaeltorbert** [comment] 2019-06-07 20:10
@michaeltorbert Does that mean there are two semi-unrelated but overlapping issues, one for each plugin?

**Comment by EkoJR** [comment] 2019-06-07 20:13
At least 1 error is unrelated to AIOSEOP. The file perms for the Classic Editor doesn't have the correct rights set up for the WP platform to remove and add files.

The long error initially shown (when it should be a WP error), does seem to be triggered by aioseop's redirect setup. Which is rather odd when it's just a WP_Error call.

**Comment by michaeltorbert** [comment] 2019-08-15 14:47
A way to test this is by implementing the redirect on some other .org plugin we have that barely is used.

**Comment by wpsmort** [comment] 2020-07-08 15:18
This will be included in the v3.6 release which is due for release this week.

**Closed by wpsmort** 2020-07-08 15:18 UTC
Labels: Bug, Has been reproduced, User Reported
