### ISSUE TITLE
Code Refactor - Support for wp_get_document_title()

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1751] opened 2018-06-25 13:59 UTC
Do we support this function? (from WP 4.4)

This is regarding the support request from e. stout via email

**Comment by michaeltorbert** [comment] 2018-06-25 15:47
After testing, we definitely do not. 
Possibly related to https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/877 https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/255

**Comment by contactashish13** [comment] 2018-10-29 13:14
@michaeltorbert I'm trying to understand what to do here but I'm not very clear. An example would help.

**Comment by michaeltorbert** [comment] 2018-11-07 16:50
****************************From the email****************************

Ref: https://www.yescbd.co.uk/shop/

Using the 'All-in-one-SEO' module, to change the various page titles to 'Subject | YES CBD', however when using the Savoy Theme AJAX menu system it defaults back to 'Subject - YES CBD'. But, if I fully reload the page the correct pipe/| separator is used.

I contacted the Savoy theme maker about this, the below was their response:

"The "wp_get_document_title()" function in the "../savoy/woocommerce/ajax/shop-full.php" template (line 23) is used when changing the page-title via AJAX.

I'm not sure why the "|" separator isn't used, but the "All in one SEO" plugin might use a filter/hook that doesn't work with this function.

It would seem that perhaps the AIO SEO plugin does not adjust/retrieve 'wp_get_document_title()', which is what the theme uses for the AJAX update. Steps to reproduce on our site, so that you can see the problem:

- Open the below:

https://www.yescbd.co.uk/shop/

- Title is shown as 'subject | YES CBD', as expected
- Use the AJAX menu, to select the 'CBD Additives' category
- Page content changes via AJAX, but the subject reverts to the default 'subject - YESCBD', NOT the expected 'subject | YES CBD'
- If you fully reload the page with a browser refresh, it changes to the expected 'subject | YES CBD'

Savoy theme author has advised the following is used by the theme:

"<?php
        /* Page title */

        if ( $nm_theme_options['shop_ajax_update_title'] ) {
        printf( '<div id="nm-wp-title">%s</div>', wp_get_document_title() );
        }
?>"

**Comment by michaeltorbert** [comment] 2018-11-07 16:50
I've linked to the theme download in slack

**Comment by contactashish13** [comment] 2018-11-15 10:21
The link in https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1751#issuecomment-436694042 does not have an ajax menu so the bug cannot be reproduced.

I installed the theme (savoy, not savoy child) on a brand new install, installed all the theme recommended by it and created a menu. Went to the home page to click on a menu item and it does not load using ajax.  I consulted their documentation http://docs.nordicmade.com/savoy/#header-menus-locations but it does not mention ajax menus.

maybe @arnaudbroes can help?

**Comment by iMiMx** [comment] 2018-12-12 15:39
Theme Settings -> Shop Filters -> AJAX

**Comment by michaeltorbert** [comment] 2019-08-15 13:44
We should wait on this until we have pulled out all the title code to its own file.

**Comment by arnaudbroes** [comment] 2019-08-15 13:44
Related to https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/255.

**Comment by wpsmort** [comment] 2020-04-07 21:25
Dupe of https://github.com/awesomemotive/aioseop-pro/issues/52

**Closed by wpsmort** 2020-04-07 21:25 UTC
Labels: Code Refactor, Priority | High
