### ISSUE TITLE
issue with sleecting an Image for social in page

### ISSUE THREAD

**Issue by holzlchr** [awesomemotive/all-in-one-seo-pack#1453] opened 2018-01-03 17:13 UTC
In editing a page
Section "All n One SEO Pack"
Tab "Social"
Image
I upload a second image
I Update

Result:
In the page I have the second image URL appearing
In my <meta property="og:image" tag, I still ave the first one
![screenshot from 2018-01-03 19-05-47](https://user-images.githubusercontent.com/28824202/34531156-1c313be2-f0ba-11e7-8c9e-13bd159dd268.png)
![screenshot from 2018-01-03 19-06-08](https://user-images.githubusercontent.com/28824202/34531157-1c617348-f0ba-11e7-855d-6fbf896dae8b.png)

**Comment by contactashish13** [comment] 2018-01-04 11:11
@michaeltorbert I've verified this on a local install and I cannot reproduce this.

**Comment by wpsmort** [comment] 2020-04-24 19:37
I'm closing this as we've never had any other reports of a problem with this feature and we've not been able to reproduce this.

**Closed** 2020-04-24 19:36 UTC
Labels: Bug
