### ISSUE TITLE
Save AIOSEOP settings on Save Draft for empty posts

### ISSUE THREAD

**Issue by H-K-P** [awesomemotive/all-in-one-seo-pack#1033] opened 2017-08-04 05:25 UTC
Hi Folks,
I just updated to Version 2.3.15.  I use Wordpress  version 4.8.1.
All was working 100% till I installed V2.3.15 and I now have issues with the 'OG:Image' on Facebook - but not Twitter.
I have a default 'OG:Image' source setting of an icon for all posts and then I manually enter a Custom URL for the author image, which should over-ride the default on individual posts.  
However, since the  V2.3.15 update, while Twitter 'twitter:image' still correctly provides the correct custom image, the Facebook 'og:image' provides the default image, instead of the custom image.
I noticed that in the past, when I saved or published a post, the SEO would automatically select (darken) the radio button under the relevant custom image - which in turn correctly changed the 'og:image' from the default, to the custom.
Now with V2.3.15, saving or publishing a post no longer automatically selects the image radio button to the custom url.  This means I need to do it manually, to get the custom image option to work on posts.
As I say, the 'twitter:image'  works fine - but there are no other options to select :)
FYI: Under Image Setting, I have 'OG:Image Source' set to 'Default Image.'
So it is working... - but not automatically.
Any chance it can be fixed so that a custom image url is automatically saved as the 'og:image', as it was in previous versions, on 'save' and 'publish'?
Regards and thanks.
Angus

**Comment by amostajo** [comment] 2017-08-04 23:27
@wpsmort I can not reproduce issue.
Custom image does save and gets selected as it should on my end. Please test.

**Comment by michaeltorbert** [comment] 2017-08-05 11:32
@H-K-P What are the exact steps to reproduce? Does the problem still occur if you disable all other plugins and switch to the default theme?

**Comment by michaeltorbert** [comment] 2017-08-06 21:50
This was also reported via Facebook by ‎Felipe.

_images are not loading anymore on facebook. we setup to have Featured Image of the post and now with the upgrade it does not work anymore._

_i did update your plugin and OG featured image stoped working. it will only display default image. eventhough featured image was selected. it was working fine before previous update. i did a debuuger on facebook and grab default image. after i updated the plugin it was working again the way ot was before._

He says it was fixed in a 2.3.15.x release, but we should try and confirm a) whether it was ever a legitimate bug to begin with and if so, b) whether it's actually fixed.

**Comment by wpsmort** [comment] 2017-08-07 21:20
@michaeltorbert I tested this on an existing site and on a new site and was unable to reproduce either issue.  I tested updating from versions 2.3.13 onwards to 2.3.15 and each time the images in the source code were correct and did not change.  I tested with Featured Image and Post Author Image.  

I also checked back to v2.3.11 and confirmed that AIOSEOP has never preselected a radial in the list of images on the Edit Post screen.  The only way a radial is selected is if the user specifically clicks on it.  If a user selects a specific image by clicking the radial then this is the image used for Facebook and Twitter. The only setting that overrides this is the Custom Twitter Image setting.

**Comment by michaeltorbert** [comment] 2017-08-07 21:22
@H-K-P Can you please provide us with exact steps to reproduce this issue?

**Comment by arnaudbroes** [comment] 2017-08-08 12:35
@michaeltorbert I tested this with a couple of different versions and this is working fine for me as well. Default image is overrided by custom images and everything in the source code seems correct. Perhaps he just had some caching issues?

**Comment by H-K-P** [comment] 2017-08-08 13:50
@michaeltorbert   Sorry for the delay in replying.
Disabling plugins makes no difference.   As @wpsmort commented above: _"AIOSEOP has never preselected a radial in the list of images on the Edit Post screen. The only way a radial is selected is if the user specifically clicks on it."_ 
I guess therefore I was getting some 'errors' in the previous version which automatically selected the custom radial on save/publish for me.  That was good for me, because it saved a couple of steps.  However, it seems that was not what you planned or designed - so there may be nothing wrong in the plugin as it now stands.
**However**, during my testing I have also found out that if I open a new post and immediately try to insert a custom image, I cannot do it.  For me, on a blank post, neither pasting in a custom image URL nor uploading a custom image will work, for on SAVE, the URL returns to blank and no image or radial is added.
Thus I can only add a custom image **if** I already have an image in the post.
I don't know if that is what you planned, but it is what I have :) 
So **on a new post** - (which already shows the default icon), I add a small author image (100x100)  before adding the custom image URL, which is the same author image, but 350x350 for Facebook use.  Finally I then select the radial on the third image, after SAVE.  See attached.
If I do not select any radial button, it will use the default icon image for Facebook, but for Twitter, will the custom URL image :)
I hope that makes sense to you.  It is not a work-around, I've been doing it that way since the start. 
All this is not an issue for me as I always have an image in all posts already,  before I add the custom one.  I just pass it on for your information.
I hope this helps.  
Regards and thanks,
Angus     

![hkp](https://user-images.githubusercontent.com/29818984/29074890-67d721d4-7c83-11e7-8f6b-ed6e3b3f71d8.jpg)

**Comment by wpsmort** [comment] 2017-08-08 15:50
@H-K-P PLease provide the exact steps to reproduce this as I cannot reproduce the problem with adding a custom image.  Follow these steps to add a custom image to a new post:

1. Go to Posts > Add New to create a new post
2. Add a title and some text content
3. In the Social Settings tab of All in One SEO Pack, click the Upload Image button
4. Upload an image to the Upload Files tab and click the Choose Image button
5. You should now see the full URL for the image in the Custom Image field
6. Publish the post
7. Go to the Social Settings tab of All in One SEO Pack and verify that the image URL is still present in the Custom Image field
8. Check the source code of the post to verify that the meta tags for og:image, twitter:image and meta image are showing the URL from the Custom Image field

If following these steps results in the correct image URL appearing in the source code of your post then All in One SEO Pack is working correctly and as it always has done.

**Comment by H-K-P** [comment] 2017-08-09 02:10
@wpsmort   Thank you.  **Matter is now resolved.**
It has often been my habit to do the 'admin' on a post, **before** inserting any content or title.  
After your last comment and some testing, I now see that if the post contents and title are blank - the Custom Image will not work.  
Adding any content or title input first, will allow the Custom Image URL to be recognized and retained on SAVE or PUBLISH.
Again, thanks very much.  Sorry to have wasted your time on this.
Regards and thanks,
Angus

**Comment by wpsmort** [comment] 2017-08-09 13:41
I have tested adding SEO meta and OG meta including a custom image to a post before adding a title and content.  Here are my results:

You cannot publish a post until you have added a title. A Post Title is the minimum required in order to publish a post, this is because a permalink is not created until a title has been entered.  Once a title has been entered then you can successfully add any SEO and OG meta including setting a custom image.  

You can save a post as a draft without any title or content.  When you click the Save Draft button on an empty post, it does not save any settings in the AIOSEOP meta box, the settings revert to empty fields.  A Post ID is created when you save an empty post and an entry is created in the postmeta table for the post ID. It may be possible to have the Save Draft action save any settings in the AIOSEOP meta box to the database.

**Closed** 2020-04-08 20:21 UTC
Labels: Initial Review, Priority | Low
