### ISSUE TITLE
switch is equivalent to "break" in aioseop_opengraph.php on line 971

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2383] opened 2019-05-04 19:06 UTC
Reported by Anatolii P. on 5/4/2019 by e-mail.

> Plugin doesn't work   and I start receiving error switch is equivalent to "break". Did you mean to use "continue 2"? in www/wp-content/plugins/all-in-one-seo-pack-pro/modules/aioseop_opengraph.php on line 971

I've requested login credentials so we access his website. He said he's using v2.12.

**Comment by michaeltorbert** [comment] 2019-07-25 10:43
Is this a duplicate of #2129

**Closed** 2020-04-29 16:38 UTC
Labels: Bug, User Reported
