### ISSUE TITLE
check for conflicting or redundant software

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#178] opened 2016-04-11 16:46 UTC
When we detect conflicting software activated (other SEO plugins, themes with SEO, the woocommerce addon that doesn't add anything, etc) we should offer to disable their features, deactivate, or import as appropriate.

**Comment by arnaudbroes** [comment] 2020-03-11 19:34
Duplicate of https://github.com/awesomemotive/all-in-one-seo-pack/issues/178.

**Closed by arnaudbroes** 2020-03-11 19:34 UTC
Labels: Conflict
