### ISSUE TITLE
XML Sitemap - Missing XML tags when Posts page doesn't exist

### ISSUE THREAD

**Issue by ARSGeek** [awesomemotive/all-in-one-seo-pack#1530] opened 2018-01-27 22:43 UTC
Hello, doing some work for a client. Upon attempting to submit their sitemap on Google Search Console, I get this error.

Missing XML tag | This required tag is missing. Please add it and resubmit. | 1 | Parent tag: urlTag: loc | 10

The sitemap settings are set to create dynamic sitemap. I've tried both ways, deactivated the sitemap feature, reactivated it. Cleared the cache, nothing works so far.

![sitemap example](https://user-images.githubusercontent.com/28026417/35477047-d9b56e6c-0380-11e8-90d2-e2d7395c1fac.JPG)

**Comment by michaeltorbert** [comment] 2018-01-28 00:27
@ARSGeek So that we can investigate this further, you can send us your login info to our secure form at https://semperplugins.com/contact/submit-login-information/

**Comment by wpsmort** [comment] 2018-01-28 18:20
@ARSGeek I found that this is caused because under "Settings > Reading > Your homepage displays" there is nothing selected in the "Posts page" dropdown.  However, it looks like this was set to a page with the ID of 1788.  I know this because in the database it has this in the wp_options table:

page_for_posts = 1788

We look at the value set in the page_for_posts database option and list that in our sitemap as the blog page.  However, because page 1788 no longer exists on your site we can't display a URL hence the missing <loc> value.  

Saving the "Reading Settings" screen without changing anything fixes this because the database option reverts back to a value of 0 which we ignore.  In fact, you have a Blog page so you could select that in the "Posts page" dropdown. 

I tried to reproduce this on a new install of WordPress to determine if this is a bug with AIOSEOP and could not reproduce it.  If I delete the page set as the "Posts page" then the database option is also deleted.  It's possible that something happened on your site where the page was deleted and the database never updated correctly.

We will look into whether we should validate the page ID set under page_for_posts to accommodate edge cases like this where the value in the wp_options table doesn't get updated correctly for some reason.

**Comment by ARSGeek** [comment] 2018-01-28 19:56
Hi,
Thanks for your thorough investigation. I hadn't thought to look under Settings
> Reading >. I did not build this website, but seeing that page 1788
doesn't exist, I went ahead and set the post page.

Google Search Console didn't find any errors after doing that and I don't
see any issue with leaving it that way now.

Really appreciate your help.



<https://www.facebook.com/ARSDigitalMarketing/>
<https://twitter.com/ARS_Marketing/>
<https://plus.google.com/+ARSDigitalMarketing/>
<https://www.linkedin.com/company/ars-digital-marketing/>
<https://www.instagram.com/ars.dm/>

**Comment by michaeltorbert** [comment] 2018-01-28 20:02
@ARSGeek Awesome. Thanks for reporting this. It's odd that it ended up that way, and who knows what the actual cause was, but we'll modify our validation so it doesn't happen in the future just in case.

**Comment by wpsmort** [comment] 2018-01-31 23:26
We should determine whether we want to add a check in our XML Sitemap code to verify the page ID set under Settings > Reading > Front page and Posts page.  Would such a check be too costly on a very large site where we have to check against tens of thousands of page IDs?

**Comment by wpsmort** [comment] 2020-04-24 19:44
@arnaudbroes I'm assigning this to you to look at as part of the V4 architecture.  If you set the page_for_posts entry in wp_options to an ID for a page that doesn't exist then you'll see we output an empty entry in the XML Sitemap.

**Comment by arnaudbroes** [comment] 2020-05-10 21:29
This shouldn't be an issue in V4 but I'll leave this open so we can test this.

**Closed** 2020-12-14 13:18 UTC
Labels: Bug, Has been reproduced, User Reported
