### ISSUE TITLE
Provide option to submit sitemap to webmaster tools using their api

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#424] opened 2016-08-10 13:18 UTC
Google, Bing, Baidu, Yandex, etc

ex: https://developers.google.com/webmaster-tools/v3/sitemaps/submit

**Comment by wpsmort** [comment] 2020-04-10 19:16
Dupe of #1456

**Closed by wpsmort** 2020-04-10 19:16 UTC
Labels: Enhancement
