### ISSUE TITLE
Add better support for modern theme titles with title-tag

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#877] opened 2017-04-12 12:16 UTC
Currently, I think that if a theme uses title-tag as they should, rather than wp_title, we're still brute-forcing it. We should verify and try to do this more gently.

make.wordpress.org/core/2014/10/29/title-tags-in-4-1/

**Comment by michaeltorbert** [comment] 2018-04-05 14:33
In testing, it doesn't even look like our OB works for this. Do we have support at all?

**Comment by wpsmort** [comment] 2020-04-07 21:20
Dupe of https://github.com/awesomemotive/aioseop-pro/issues/52

**Closed by wpsmort** 2020-04-07 21:20 UTC
Labels: Needs Discussion, Optimization, Priority | Medium
