### ISSUE TITLE
Marketing - Add placeholder/upsell for cat/tag/tax titles

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#738] opened 2017-01-31 07:31 UTC
We should have an upgrade to pro placehold on the edit category/taxonomy screen as well as columns. This is an upsell so that they can have AIOSEOP on this page.

**Comment by contactashish13** [comment] 2019-03-08 13:35
@michaeltorbert is something like this already being shown in the plugin that I can get inspired from? If not, can you share the kind of UI you are looking for this?

I can think of the below:

- a link like the ones we usually see on the plugins listing page along with the plugin actions
- an admin info notification like some plugins show

I think it would also be a good idea to make this generic so that it can be extended to more screens if required.

**Comment by michaeltorbert** [comment] 2019-03-08 14:16
@contactashish13 For now let's do a non-dismissible admin notice that only shows up on these pages.

**Comment by contactashish13** [comment] 2019-03-09 05:02
will not address this in 3.0 as this has been moved to 3.1 by @arnaudbroes

**Comment by arnaudbroes** [comment] 2019-03-11 08:46
@contactashish13 there was some confusion going on between Michael and myself. Ideally this is added in 3.0, so I corrected the milestone.

**Comment by contactashish13** [comment] 2019-03-18 09:57
@arnaudbroes what should the placeholder text read?

**Comment by arnaudbroes** [comment] 2019-03-18 14:26
@contactashish13 "Want to control SEO for Categories, Tags and other Taxonomies? <a href="https://semperplugins.com/all-in-one-seo-pack-pro-version/" target="blank">Upgrade to All in One SEO Pack Pro and unlock our premium features.</a>"

**Comment by contactashish13** [comment] 2019-03-18 14:49
PR https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2300

**Comment by michaeltorbert** [comment] 2019-03-20 21:53
This should be something with an eye catching design, as it's essentially an advertisement.

**Comment by arnaudbroes** [comment] 2019-03-20 23:04
@EkoJR will create a non-dismissable notice for this using his new class.

**Comment by arnaudbroes** [comment] 2020-03-11 19:35
Duplicate of https://github.com/awesomemotive/aioseop-pro/issues/72

**Closed by arnaudbroes** 2020-03-11 19:35 UTC
Labels: Priority | Medium, UX
