### ISSUE TITLE
long meta description showing shortcodes

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1490] opened 2018-01-17 20:44 UTC
Reported here: https://wordpress.org/support/topic/description-with-divi/

> With the latest version of All In One SEO, there is an incompatibility with divi into the meta long description.

> All the shortcode of the theme appears.

> View  [screenshot](http://www.bs-conseil.me/temp/screenshot-2018-1-16.png)

**Comment by EkoJr** [comment] 2018-01-19 20:00
I looks like this is old data from Google. I've tried to reproduce this with the recent two versions, and fetch as google to see if there was anything different; everything is currently running like it should.

When I went to search for the website, and then to a cached page with the same issue. I found that this was during 2.4.3 of aioseop (site currently running 2.4.4; current RC 2.4.4.1), but now is no longer an issue.

![i-1490-divi-descriptions](https://user-images.githubusercontent.com/2794445/35169065-f938f244-fd0f-11e7-95aa-dec18595181b.PNG)

I could test for that version, but I believe the problem can be fixed by manually going into Google's Webtools, Fetch as Google, and then Request Indexing of a specific URL. This may also lead the client to other issues as to why Google isn't indexing those URLs.

**Closed** 2020-04-10 20:52 UTC
Labels: Conflict, Needs Reproducing, User Reported
