### ISSUE TITLE
bug for "Use noindex for Categories"

### ISSUE THREAD

**Issue by yvano403** [awesomemotive/all-in-one-seo-pack#3161] opened 2020-03-26 18:11 UTC
Please fill out this form as completely as possible so that we can help you more quickly.

- [ X] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.
 - [ X] I've followed the [troubleshooting steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack)  to determine if there's a theme/plugin conflict. 

**Provide the relevant URL(s) here**

view-source:https://www.acteurdurable.org/developpement-durable/energies-renouvelables/

**Describe the bug**
i have a bug with settings "Use noindex for Categories", 
it is not selected in back (as you can see here https://prnt.sc/rnbrtm ), 
but still appear in source code : <meta name="robots" content="noindex, follow" />

**To Reproduce**

1. Go to '.https://www.acteurdurable.org/developpement-durable/energies-renouvelables/'
2. Click on '.view source code'
3. See error the code <meta name="robots" content="noindex, follow" />
4. see my screenshot https://prnt.sc/rnbrtm

**Expected behavior**
fix the bug

**Screenshots**
https://prnt.sc/rnbrtm
all other settings are ok, meens that if i uncheck Default to NOINDEX for "page" <meta name="robots" content="noindex, follow" /> desapear from source code

**Version Info (please complete the following information):**
 - WordPress version: 5.3.2 
 - All in One SEO Pack version: 3.3.5
 - PHP version: 7.0

**Comment by wpsmort** [comment] 2020-03-26 18:13
Dupe of #3160

**Closed by wpsmort** 2020-03-26 18:13 UTC
Labels: Invalid
