### ISSUE TITLE
An error of type E_ERROR was caused in line 446 of the file aioseop_sitemap.php

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2674] opened 2019-06-18 01:52 UTC
Reported via email, I'm not sure how to reproduce it.

Error Details
=============
An error of type E_ERROR was caused in line 446 of the file /home/laugol11/goldenkeypartnership.com/wp-content/plugins/all-in-one-seo-pack-pro/modules/aioseop_sitemap.php. Error message: Uncaught Error: Call to a member function deactivate_notice() on null in /home/laugol11/goldenkeypartnership.com/wp-content/plugins/all-in-one-seo-pack-pro/modules/aioseop_sitemap.php:446
Stack trace:
#0 /home/laugol11/goldenkeypartnership.com/wp-includes/class-wp-hook.php(286): All_in_One_SEO_Pack_Sitemap->sitemap_notices('')
#1 /home/laugol11/goldenkeypartnership.com/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /home/laugol11/goldenkeypartnership.com/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /home/laugol11/goldenkeypartnership.com/wp-admin/admin-ajax.php(45): do_action('admin_init')
#4 {main}
  thrown

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/b07ef0b86a22450eb242fb06459d242f13c4774b/modules/aioseop_sitemap.php#L446

**Comment by wpsmort** [comment] 2020-04-29 16:46
I'm closing this as we can't reproduce it

**Closed** 2020-04-29 16:46 UTC
Labels: Bug, Needs Reproducing, User Reported
