### ISSUE TITLE
Missing XML tag with WPML plugin active

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1541] opened 2018-02-02 19:51 UTC
Reported here: https://wordpress.org/support/topic/missing-xml-tag-11/

**Comment by michaeltorbert** [comment] 2018-02-03 04:03
This may be a dupe of #1530

**Comment by EkoJr** [comment] 2018-02-04 23:24
I took a look at this, and I don't think this is a dupe of #1530. I noticed it does seem a similar to #1428, but I'm still unsure if it is directly related.

I investigated the site and found the sitemaps with problems weren't being downloaded and displayed as text, and I believe it could be an issue with the Content Headers; which seems a bit unrelated...but I also have some suspicions with the file. 

While testing, I ran into this error multiple times; which seems to prevent the gzip header.

```

( ! ) Warning: Cannot modify header information - headers already sent by (output started at C:\WebProjects\aioseop\sitepress-multilingual-cms\lib\dqml2tree.php:475) in C:\WebProjects\aioseop\src\modules\aioseop_sitemap.php on line 1242
--


1 | 0.0004 | 392080 | {main}( ) | ...\index.php:0
2 | 0.0007 | 393744 | require( 'C:\WebProjects\aioseop\WordPress\wp-blog-header.php' ) | ...\index.php:17
3 | 1.0709 | 39720120 | wp( ) | ...\wp-blog-header.php:16
4 | 1.0709 | 39720144 | WP->main( ) | ...\functions.php:960
5 | 1.0719 | 39732976 | WP->query_posts( ) | ...\class-wp.php:715
6 | 1.0719 | 39733024 | WP_Query->query( ) | ...\class-wp.php:599
7 | 1.0719 | 39732752 | WP_Query->get_posts( ) | ...\class-wp-query.php:3222
8 | 1.0719 | 39732752 | WP_Query->parse_query( ) | ...\class-wp-query.php:1621
9 | 1.0721 | 39735192 | do_action_ref_array( ) | ...\class-wp-query.php:1006
10 | 1.0721 | 39735192 | WP_Hook->do_action( ) | ...\plugin.php:515
11 | 1.0721 | 39735192 | WP_Hook->apply_filters( ) | ...\class-wp-hook.php:310
12 | 1.0736 | 39813344 | All_in_One_SEO_Pack_Sitemap->sitemap_output_hook( ) | ...\class-wp-hook.php:286
13 | 1.0737 | 39813432 | header ( ) | ...\aioseop_sitemap.php:1242
```

```

( ! ) Warning: Cannot modify header information - headers already sent by (output started at C:\WebProjects\aioseop\sitepress-multilingual-cms\lib\dqml2tree.php:475) in C:\WebProjects\aioseop\src\modules\aioseop_sitemap.php on line 1249
--


1 | 0.0004 | 392080 | {main}( ) | ...\index.php:0
2 | 0.0007 | 393744 | require( 'C:\WebProjects\aioseop\WordPress\wp-blog-header.php' ) | ...\index.php:17
3 | 1.0709 | 39720120 | wp( ) | ...\wp-blog-header.php:16
4 | 1.0709 | 39720144 | WP->main( ) | ...\functions.php:960
5 | 1.0719 | 39732976 | WP->query_posts( ) | ...\class-wp.php:715
6 | 1.0719 | 39733024 | WP_Query->query( ) | ...\class-wp.php:599
7 | 1.0719 | 39732752 | WP_Query->get_posts( ) | ...\class-wp-query.php:3222
8 | 1.0719 | 39732752 | WP_Query->parse_query( ) | ...\class-wp-query.php:1621
9 | 1.0721 | 39735192 | do_action_ref_array( ) | ...\class-wp-query.php:1006
10 | 1.0721 | 39735192 | WP_Hook->do_action( ) | ...\plugin.php:515
11 | 1.0721 | 39735192 | WP_Hook->apply_filters( ) | ...\class-wp-hook.php:310
12 | 1.0736 | 39813344 | All_in_One_SEO_Pack_Sitemap->sitemap_output_hook( ) | ...\class-wp-hook.php:286
13 | 1.1489 | 39813368 | header ( ) | ...\aioseop_sitemap.php:1249
```

**Comment by EkoJr** [comment] 2018-02-13 23:25
After setting up the environment with WPML, and producing the error above. I was lead to suspect WPML plugin is where the root issue is, and reported the issue with WPML Support; since a workaround seems near-impossible. 

[The each() deprecated causes post-issues `Cannot modify header information`](https://wpml.org/forums/topic/the-each-deprecated-causes-post-issues-cannot-modify-header-information/)

I've also seen this issue across other plugins as well as WP itself.

What is happening is....WPML uses a deprecated function `each()`, which is part of `create_function()` and was removed with PHP ~7.1. In turn, it causes a strange issue with the instance to hanging onto an older instance to finish as part of the translation with the SQL query. 

This is fixed with WPML 4.0, unfortunately at this moment no release date has been determined, and there seems to be no workaround; other than suppressing the errors.

**Comment by EkoJr** [comment] 2018-02-13 23:39
The title may need to be changed to `Missing XML tag with WPML plugin active`.

**Comment by wpsmort** [comment] 2020-04-24 20:03
Closing this as it looks to be fixed now.

**Closed** 2020-04-24 20:03 UTC
Labels: Bug, User Reported
