### ISSUE TITLE
All-in-one-seo causes classic editor to insert link twice

### ISSUE THREAD

**Issue by esolix** [awesomemotive/all-in-one-seo-pack#3172] opened 2020-04-25 04:36 UTC
Please fill out this form as completely as possible so that we can help you more quickly.

- [x] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.
 - [x] I've followed the [troubleshooting steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack)  to determine if there's a theme/plugin conflict. 

**Provide the relevant URL(s) here**

**Describe the bug**
All-in-one-seo causes double link insertion on classic editor "text mode"

What happened?

Since the upgrade from 3.4.2 all our sites are experiencing duplicated link insertion issue with classic editor plugins in "text mode" - It does not happen with Visual Mode.

What did you expect to happen?
Single link insertion.

**To Reproduce**
1. Go to 'Create a post -> Text mode tab on editor'
2. Click on 'Write some text in TEXT MODE - select text and click on "LINK" button'
3. Type in URL and enter
4. Link will be inserted twice like
`<a href="http://test.com">test</a><a href="http://test.com">test</a>`

**Expected behavior**
Insert only a single text such as 
`<a href="http://test.com">test</a>`

**Version Info (please complete the following information):**
 - WordPress version: 5.4
 - All in One SEO Pack version: 3.4.3
 - PHP version: 7.2.30

**Comment by wpsmort** [comment] 2020-04-25 14:08
Closing this as it's a dupe of an issue open in our private repo here - https://github.com/awesomemotive/aioseop-pro/issues/885

**Closed by wpsmort** 2020-04-25 14:08 UTC
