### ISSUE TITLE
multisite: “array_key_exists() expects parameter 2 to be array… in modules/aioseop_robots.php on line 315”

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2322] opened 2019-03-29 10:28 UTC
Reported here - https://wordpress.org/support/topic/robots-module-throws-error-array_key_exists-in-multisite/

> In multisite configuration I got error “array_key_exists() expects parameter 2 to be array… in modules/aioseop_robots.php on line 315”, when calling http…/robots.txt
> Apparently “$options = get_option(‘aioseop_options’)” in line 311 is not handled for “false” values coming from other blogs. 

>This snippet above line 315 resolved the issue:
> if ( $options === false ) { return( array() ); }

@EkoJR can you review this at some point?

**Comment by wpsmort** [comment] 2020-04-29 16:37
Closing this as we can't reproduce this and have no other reports.

**Closed by wpsmort** 2020-04-29 16:37 UTC
Labels: Bug, User Reported
