### ISSUE TITLE
Broken fields

### ISSUE THREAD

**Issue by jan-71** [awesomemotive/all-in-one-seo-pack#2557] opened 2019-06-04 12:22 UTC
After an update to version version 3.0, the fields are broken and can not be clicked.
![bug1](https://user-images.githubusercontent.com/51368601/58878727-33b1f480-86d4-11e9-9b49-45f1dd28ba28.jpg)
![bug2](https://user-images.githubusercontent.com/51368601/58878728-33b1f480-86d4-11e9-91bc-bed7634fdb97.jpg)

**Comment by michaeltorbert** [comment] 2019-06-04 12:49
Hi @jan-71 

Thank you for reporting this. So far we've been unable to reproduce it.
You can submit your login information to our secure form here and we'll investigate further.

**Comment by michaeltorbert** [comment] 2019-06-04 14:36
Hi @jan-71 

Thank you for reporting this. So far we've been unable to reproduce it.
You can submit your login information to our secure form here and we'll investigate further. 
https://semperplugins.com/contact/support-login-information/

**Comment by wpsmort** [comment] 2019-06-04 18:56
@jan-71 Do you have a caching or performance plugin installed that is doing both caching and CSS / JavaScript minification?

**Comment by wpsmort** [comment] 2019-06-04 22:07
I was able to reproduce this on a site and found that it was caused by WP Fastest Cache.  Clicking the option to Delete the cache and minified CSS/JS fixed the problem.

**Comment by michaeltorbert** [comment] 2019-06-04 22:21
Why would our CSS/JS be cached? Doesn't WP automatically bust it with file.css?version=x?
@EkoJR?

**Comment by EkoJR** [comment] 2019-06-05 03:58
Using a different version should force the cache to refresh if it is cache.

This could possible a client side issue. Doing a Hard Refresh on the browser might fix the issue.

**Comment by jan-71** [comment] 2019-06-05 08:44
I cleared the cache and temporarily disabled WP Fastest Cache, but the issue continues. I have not installed any additional caching plugins. It has to be a CSS problem. The problem also occurs only with the plugin version 3.

**Comment by jan-71** [comment] 2019-06-05 08:55
@wpsmort yes WP Fastest Cache. I have cleared Cache and minified CSS/JS. but the issue continues.

**Comment by jan-71** [comment] 2019-06-05 08:58
Here is a list of the active plugins:

All In One SEO Pack
    3.0.1
    Anti-spam
    5.4
    Better Search Replace
    1.3.3
    Classic Editor
    1.5
    Contact Form 7
    5.1.3
    Contact Form 7 Image Captcha
    2.4.7
    Cookie Notice
    1.2.46
    Custom Permalinks
    1.5.0
    Easy Custom Auto Excerpt
    2.4.10
    Google Image Sitemap Feed With Multisite Support
    1.2.0.4
    HTML in Category Descriptions
    1.2.1.1
    iThemes Security
    7.3.3
    LuckyWP Table of Contents
    1.5
    Meta Generator and Version Info Remover
    6.0.1
    Post Type Switcher
    3.1.0
    Really Simple SSL
    3.1.5
    Schema
    1.7.5
    Search & Replace
    3.2.0
    Simple 301 Redirects
    1.07
    Simple Price Calculator 1.4
    1.4
    Wordfence Security
    7.3.2
    WordPress Importer
    0.6.4
    WordPress Notification Bar
    1.3.9
    WordPress Related Posts Thumbnails
    1.7.1
    WP Health (Formerly My WP Health Check)
    1.8.5

**Comment by michaeltorbert** [comment] 2019-06-05 12:59
@jan-71 
Unfortunately we can't fix what we can't reproduce.
If  you would like us to investigate this issue, we'll need to access your site.
https://semperplugins.com/contact/support-login-information/

**Comment by wpsmort** [comment] 2019-06-12 18:16
This can be reopened if we get more info such as steps to reproduce.

**Comment by jan-71** [comment] 2019-06-13 08:00
I have not been in the office for a couple of days, so I'm only getting in touch now. I found the mistake. There is a conflict with the nginx pagespeed module. The nginx Pagespeed module optimizes css files. If I deactivate the nginx Pagespeed module also the admin area of the all in one seo pack is displayed correctly again. But when I turn on nginx pagespeed again, the CSS error reappears.

**Comment by wpsmort** [comment] 2020-04-14 19:18
I'm closing this as it appears to be due to the CSS optimization being done by this NGINX Pagespeed module and not our plugin.  We've had no other reports of this issue from any other user or any other release.

**Closed by wpsmort** 2020-04-14 19:18 UTC
Labels: Conflict, Needs Reproducing, User Reported
