### ISSUE TITLE
Bug - Autogenerated OG descriptions broken with Enfold theme v4.5.5

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2307] opened 2019-03-20 17:37 UTC
@InoPlugs fixed #2120 but this in turn broke autogenerated OG descriptions. I'm reaching out to him to see what caused this.

Reported by Iskan I. on 3/20/2019 via e-mail.

**Comment by InoPlugs** [comment] 2019-03-21 13:16
@arnaudbroes 
@michaeltorbert 

Please check https://github.com/KriesiMedia/enfold-library/blob/master/temp_fixes/Enfold_4_5_5/AIO_SEO/shortcode-template.class.php

Replace enfold\config-templatebuilder\avia-template-builder\php\shortcode-template.class.php with the content of this file.

Look at line 388:

```
$preprocess = apply_filters( 'avf_preprocess_shortcode_in_header', avia_get_option( 'preprocess_shortcodes_in_header', '' ), $this, $atts, $content, $shortcodename, $fake );
```

I added an option where user can enable this. I'm not sure if Kriesi likes this option, but the filter should remain. 

Pleasde check if it solves the problem.

**Comment by michaeltorbert** [comment] 2019-03-21 13:18
@InoPlugs Please don't tag me in issues unless I specifically am needed.

**Comment by Isambel** [comment] 2019-03-25 18:09
@InoPlugs I did replaced enfold\config-templatebuilder\avia-template-builder\php\shortcode-template.class.php with the content of this file, and nothing changed, same issue.

I’m not seeing a meta description, og:description and twitter:description in the section in the source code of my site. 

You can check it here: http://u4425-elevated-372.qsandbox.com/a-nice-entry/

Thanks,
Iskan

**Comment by InoPlugs** [comment] 2019-03-26 06:34
@Isambel 

Did you use the filter to activate it (see line 308 ff) ?

**Comment by Isambel** [comment] 2019-03-26 15:31
@InoPlugs Sorry, no I did not, where's it? how do I activate it?

**Comment by InoPlugs** [comment] 2019-03-27 11:53
@Isambel 

Mentioned above: 
enfold\config-templatebuilder\avia-template-builder\php\shortcode-template.class.php line 308.
```

add_filter( 'avf_preprocess_shortcode_in_header', 'custom_avf_preprocess_shortcode_in_header', 10, 6 );

function custom_avf_preprocess_shortcode_in_header( $return, $class,  $atts, $content, $shortcodename, $fake )
{
	return 'preprocess_shortcodes_in_header';
}


```

**Comment by Isambel** [comment] 2019-03-27 20:46
@InoPlugs it worked, I added the filter in function.php 
Testing: http://u4425-elevated-372.qsandbox.com/a-nice-entry/

Thank you!

**Comment by Isambel** [comment] 2019-03-28 17:35
@InoPlugs another issue is that Autogenerate Descriptions includes now  <h1>–<h6>: The HTML Section Heading elements which come before the content, except the content itself 
So it looks like this now 
<meta name="description"  content="<h1>–<h6>Lorem ipsum dolor sit amet, consectetuer adipiscing... " />
How do I get rid of <h1>–<h6> in the content descriptions ?

Testing: http://u4425-elevated-372.qsandbox.com/a-nice-entry/ Access Code: 1234
Thanks!

**Comment by InoPlugs** [comment] 2019-04-01 10:16
@Isambel 

Checking your link above: cannot see h1-h6 in page content (FireFox right click "Show page content").
```

<!-- All in One SEO Pack Pro 2.13 by Michael Torbert of Semper Fi Web Design[1080,1123] -->
<!-- Debug String: 4T+7HJUKPKQB8GW9PXGF7PV3/7S -->
<meta name="description"  content="test Ref: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis" />

<link rel="canonical" href="http://u4425-elevated-372.qsandbox.com/a-nice-entry/" />
<meta property="og:title" content="A nice entry | My qSandbox Test Site" />
<meta property="og:type" content="article" />
<meta property="og:url" content="http://u4425-elevated-372.qsandbox.com/a-nice-entry/" />
<meta property="og:image" content="http://u4425-elevated-372.qsandbox.com/wp-content/plugins/all-in-one-seo-pack-pro/images/default-user-image.png" />
<meta property="og:site_name" content="My qSandbox Test Site" />
<meta property="og:description" content="test Ref: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Nunc nec neque. Phasellus leo dolor, tempus non, auctor et, hendrerit quis, nisi. Curabitur ligula sapien, tincidunt non, euismod vitae, posuere imperdiet, leo. Maecenas malesuada. Praesent congue erat at massa. Sed cursus turpis vitae tortor. Donec posuere vulputate arcu" />
<meta property="article:tag" content="food" />
<meta property="article:tag" content="fun" />
<meta property="article:tag" content="news" />
<meta property="article:tag" content="uncategorized" />
<meta property="article:published_time" content="2014-08-24T18:56:26Z" />
<meta property="article:modified_time" content="2019-03-25T18:12:52Z" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:title" content="A nice entry | My qSandbox Test Site" />
<meta name="twitter:description" content="test Ref: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Nunc nec neque. Phasellus leo dolor, tempus non, auctor et, hendrerit quis, nisi. Curabitur ligula sapien, tincidunt non, euismod vitae, posuere imperdiet, leo. Maecenas malesuada. Praesent congue erat at massa. Sed cursus turpis vitae tortor. Donec posuere vulputate arcu" />
<meta name="twitter:image" content="http://u4425-elevated-372.qsandbox.com/wp-content/plugins/all-in-one-seo-pack-pro/images/default-user-image.png" />
<meta itemprop="image" content="http://u4425-elevated-372.qsandbox.com/wp-content/plugins/all-in-one-seo-pack-pro/images/default-user-image.png" />
<!-- /all in one seo pack pro -->

```

**Comment by Isambel** [comment] 2019-04-01 13:15
@InoPlugs    test Ref: - > is <H1> 
Please check in page content (FireFox or Chrome right click "Show page content").
Fyi. This is Heading - > (H1-H6 testing Ref: github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2307 H1-H6 Ends here)

http://u4425-elevated-372.qsandbox.com/a-nice-entry/ Access Code: 1234




<meta name="description"  content="H1-H6 testing Ref: github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2307 H1-H6 Ends here Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean" />

<link rel="canonical" href="http://u4425-elevated-372.qsandbox.com/a-nice-entry/" />
<meta property="og:title" content="A nice entry | My qSandbox Test Site" />
<meta property="og:type" content="article" />
<meta property="og:url" content="http://u4425-elevated-372.qsandbox.com/a-nice-entry/" />
<meta property="og:image" content="http://u4425-elevated-372.qsandbox.com/wp-content/plugins/all-in-one-seo-pack-pro/images/default-user-image.png" />
<meta property="og:site_name" content="My qSandbox Test Site" />
<meta property="og:description" content="H1-H6 testing Ref: github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2307 H1-H6 Ends here Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Nunc nec neque. Phasellus leo dolor, tempus non, auctor et, hendrerit quis, nisi. Curabitur ligula sapien, tincidunt non, euismod vitae, posuere imperdiet, leo. Maecenas malesuada. Praesent congue erat at massa. Sed cursus turpis vitae tortor. Donec posuere" />
<meta property="article:tag" content="food" />
<meta property="article:tag" content="fun" />
<meta property="article:tag" content="news" />
<meta property="article:tag" content="uncategorized" />
<meta property="article:published_time" content="2014-08-24T18:56:26Z" />
<meta property="article:modified_time" content="2019-04-01T13:11:04Z" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:title" content="A nice entry | My qSandbox Test Site" />
<meta name="twitter:description" content="H1-H6 testing Ref: github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2307 H1-H6 Ends here Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Nunc nec neque. Phasellus leo dolor, tempus non, auctor et, hendrerit quis, nisi. Curabitur ligula sapien, tincidunt non, euismod vitae, posuere imperdiet, leo. Maecenas malesuada. Praesent congue erat at massa. Sed cursus turpis vitae tortor. Donec posuere" />
<meta name="twitter:image" content="http://u4425-elevated-372.qsandbox.com/wp-content/plugins/all-in-one-seo-pack-pro/images/default-user-image.png" />
<meta itemprop="image" content="http://u4425-elevated-372.qsandbox.com/wp-content/plugins/all-in-one-seo-pack-pro/images/default-user-image.png" />



Thanks,

**Comment by InoPlugs** [comment] 2019-04-01 16:10
@Isambel 

I your first link you gave me the output is correct:

`<meta property="og:description" content="test Ref: Lorem ipsum dolor sit amet, consect .....`

What did you enter in the heading text?

Whatever is added to the meta is nothing to do with Enfold. That must be handled by the plugin and not by the theme. We offer only the filters.

**Comment by Isambel** [comment] 2019-04-01 16:58
@InoPlugs In my first link I gave you the output is absolutely incorrect. 

Check it please here http://u4425-elevated-372.qsandbox.com/a-nice-entry/
content="H1-H6 this is Heading TEXT!!! Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque" 

it should not work like that...

Unfortunately, there are no such filters that can we can remove HEADING in the Autogenerate Descriptions.

The problem is that it happens only with ENFOLD 4.5.5 theme and All in One SEO Pack Pro 2.13. I'm not sure if this is the plugin issue now.

P.S. version All in One SEO Pack Pro 2.9 works fine, it's pulling only Autogenerate Descriptions without Headings.

**Comment by InoPlugs** [comment] 2019-04-02 08:46
@Isambel 

As much as I can see in the HTML structure you used a "Special Heading" element and as Heading Text you entered:

`H1-H6 this is Heading TEXT!!!`

And this is correct wrapped in h1 tags in the HTML structure.

If you do not like h1 - h6 tags in the meta this is the job of the plugin to filter what is needed or not.

Running the shortcodes in the content filter MUST output everything.

**Comment by wpsmort** [comment] 2020-04-14 21:03
I'm closing this as All in One SEO is working correctly in this instance.  We take the first 160 characters of the content as the auto generated SEO description (first 200 characters for the OG description).  We don't check how the content is formatted.  Text can be formatted as an H1 tag but if it's in the content then we'll use it.  All in One SEO has always worked this way ever since we added this feature in v2.

**Closed by wpsmort** 2020-04-14 21:03 UTC
Labels: Conflict, Has been reproduced, User Reported
