### ISSUE TITLE
All in One SEO Pack: Error 2.9.1 in line 3868

### ISSUE THREAD

**Issue by k008** [awesomemotive/all-in-one-seo-pack#2054] opened 2018-11-13 07:11 UTC
Hello, I updated the plugins on the site today and there was an error from all-in-one-seo-pack:
`in_array() expects parameter 2 to be array, null given in /wp-content/plugins/all-in-one-seo-pack/aioseop_class.php on line 3868`

Tell me how to solve this problem;
How can I turn off error output on the site (I tried various options - it did not help)

WP version 4.9.8
All in One SEO Pack: 2.9.1

**Comment by k008** [comment] 2018-11-13 17:06
Other users also complain:
https://wordpress.org/support/topic/php-error-in_array-expects-parameter-2-to-be-array-null-given/

I have a dynamic home page.
If in the SEO settings I choose a static main page, then the problem disappears, but this is incorrect, right?

**Comment by k008** [comment] 2018-11-13 17:25
It seems I understood, after updating my homepage's html code, it disappeared:
`<link rel = "canonical" href = "http: //domain.dom/" />`
Rummaging in SEO settings:
No Pagination for Canonical URLs

I turned on the option and the problem disappeared, turned off the option and the problem did not appear, but in the code I found `<link rel = "canonical" href = "http: //domain.dom/" />`

Most likely when updating the value of the variable is lost and because of this error ...

Related link:
https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/4012f3963f9854fad0475eaf974eb1eee62598f9

**Comment by k008** [comment] 2018-11-18 18:35
Unfortunately I can not, the problem has disappeared.
I do not even know the previous version of the All in One SEO Pack.

I have already described my steps, I do not know what to add ...
Install WP and All in One SEO Pack, try to reproduce the error?

**Comment by michaeltorbert** [comment] 2018-11-19 02:03
From looking at the code my guess is this happens when the options haven’t been saved. To reproduce, I’d recommend trying installing it on a fresh site and looking at the front-end (which is where this code runs) without saving the options.

To fix we can Probably just check whether the array exists first.

**Comment by k008** [comment] 2018-11-19 05:08
The hoster has a backup of my site. Today he will give me a copy of the site, try to restore it to another place and give access

**Comment by arnaudbroes** [comment] 2018-11-20 12:33
@michaeltorbert I tried that, but wasn't able to reproduce the issue.

**Comment by k008** [comment] 2018-11-20 18:06
@arnaudbroes, @michaeltorbert, @wpsmort 
Unfortunately, I could not reproduce from my backup, because I deployed it on another server.
Now I am working on deploying on the server, where the problem was revealed.

**Comment by k008** [comment] 2018-11-27 17:32
@arnaudbroes, @michaeltorbert, @wpsmort 

It turned out to set up a test environment.

So, when the error display is turned off, the error is not displayed (although it was shown on the working site), so I turned on the error output.

All that is required:
1. Go to admin panel
2. Update plugin
3. The error has already appeared

Login and password sent via the form, indicating this ticket

Ps.
If necessary, I can restore the state of the site, to the current moment, if you want to check again.

**Comment by k008** [comment] 2018-11-27 17:33
@wpsmort 
I'm sorry, I ran the check ...

Now everything works.

FTP is not available, I get access via ssh, now I will send data

**Comment by wpsmort** [comment] 2018-11-27 17:37
@k008 Thanks, I have access now.  I updated All in One SEO Pack to v2.9.1 but don't see the error anywhere.

**Comment by k008** [comment] 2018-11-27 17:45
@wpsmort 
Restored the site, updated the plugin and the error ...
Just in case, I copy backups to my computer, then I will provide access to the files.

**Comment by wpsmort** [comment] 2018-11-27 18:57
I tracked down the problem to the aiosp_cpostactive option not being present in the aioseop_options array in the database table.  If I export the AIOSEOP settings from the test site then aiosp_cpostactive = 'a:2:{i:0;s:4:"post";i:1;s:4:"page";}' is missing.  If I add that then the problem is resolved.  Clicking Update Options in the plugin General Settings also resolves this because it adds that option to the database.

To reproduce this, follow these steps:
1. Install AIOSEOP v2.9.1 on a fresh WordPress install
2. Export the settings using our Importer / Exporter module
3. Edit the exported file and delete the line for aiosp_cpostactive
4. Reset all settings in AIOSEOP and the import the modified file
5. Visit the homepage and the PHP warning should appear in the source code (WP_DEBUG must be enabled)

**Comment by k008** [comment] 2018-11-27 19:06
Need to install a new wp or restore test site?
You yourself can do it on your site or I have specific hosting settings

**Comment by wpsmort** [comment] 2018-11-27 19:09
@k008 We don't need your test site any more.  We've been able to reproduce this.  The error can easily be resolved by clicking the Update Options button on the General Settings screen of All in One SEO Pack.  This adds the missing option to the database table which dismisses the error message.

**Comment by k008** [comment] 2018-11-27 19:11
Sorry, got it.
My help is no longer required?

**Closed** 2020-04-28 21:35 UTC
Labels: Bug, Has been reproduced

**Comment by wpsmort** [comment] 2020-04-28 21:38
I'm closing this as the v4 architecture should take care of instances such as this.
