### ISSUE TITLE
Importing meta data only works on the same, existing website

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2068] opened 2018-11-19 21:33 UTC
If you migrate post data through the Importer/Exporter module, then entries will look like this:

```
post_title = 'TEST'
post_guid = 'http://wordpress-204735-667700.cloudwaysapps.com/?p=11'
post_date = '2018-11-19 20:58:58'
post_type = 'post'
_aioseop_description = 'This is a title.'
_aioseop_title = 'This is a description.'
```

If I'm not mistaken, then the URL is hardcoded as the GUID, which means that you can only import post data on the same, existing website as where the data was originally exported. 

Can someone confirm this? If this is the case, we should find a better way to do this so you can import data into new websites as well.

**Comment by EkoJR** [comment] 2018-11-20 02:31
My initial thoughts...I believe what could be happening is both/either the Guid & URL are getting saved. Presumably, both would reflect the old site, and both should be a new value (guid is a global unique identifier [added upon creation]), not the old value.

**Comment by wpsmort** [comment] 2020-04-10 17:57
Dupe of #2259

**Closed by wpsmort** 2020-04-10 17:57 UTC
Labels: Enhancement
